spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  messages:
    basename: i18n/messages
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 1872744675@qq.com #发送邮件的邮箱地址
    password: ktxttfsqpmzqegig #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

mail:
  from: ${spring.mail.username} # 发送邮件的地址，和上面username一致

comment.avatar: /images/avatar.png
message.avatar: /images/avatar.png
